[features]
seeds = false
skip-lint = false
[programs.devnet]
shadowmedia = "ESfupR6JYGqkYE99f611KvK8e8DCUKRXh9i3tkgcoaW1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/sven/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
